{% set name = "acme" %}
{% set version = "2.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/acme-{{ version }}.tar.gz
  sha256: f1f700ce60d84512fcd19a887f03557fd58e861b3fa061861f90cb90fdbbf208

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - cryptography >=3.2.1
    - josepy >=1.13.0
    - pyopenssl >=17.5.0,!=23.1.0
    - pyrfc3339
    - python >=3.8
    - pytz >=2019.3
    - requests >=2.20.0
    - setuptools >=41.6.0

test:
  imports:
    - acme
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/certbot/certbot
  summary: ACME protocol implementation in Python
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nehaljwani
