{% set name = "acme" %}
{% set version = "4.2.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/acme-{{ version }}.tar.gz
  sha256: 0df68c0e1acb3824a2100013f8cd51bda2e1a56aa23447449d14c942959f0c41

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - cryptography >=43.0.0
    - josepy >=2.0.0
    - pyopenssl >=25.0.0
    - pyrfc3339
    - python >={{ python_min }}
    - pytz >=2019.3
    - requests >=2.20.0
    - setuptools >=41.6.0

test:
  imports:
    - acme
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/certbot/certbot
  summary: ACME protocol implementation in Python
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nehaljwani
