{% set name = "acme" %}
{% set version = "3.1.0" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/acme-{{ version }}.tar.gz
  sha256: 39ae0032834585e5c893d7865a5867af01598b5ebef688edb54e9f11cb89ccd9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - cryptography >=3.2.1
    - josepy >=1.13.0,<2
    - pyopenssl >=17.5.0,!=23.1.0
    - pyrfc3339
    - python >={{ python_min }}
    - pytz >=2019.3
    - requests >=2.20.0
    - setuptools >=41.6.0

test:
  imports:
    - acme
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/certbot/certbot
  summary: ACME protocol implementation in Python
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nehaljwani
